import { Prisma, type PrismaClient, type SlotType, type StatAttribute } from "@prisma/client";

// Каталог снаряжения (ранее — packages/db/seed/data/Gob_markets.csv, экспорт из
// Google Sheets клиента). Данные перенесены в TS ради единообразного хранения
// сидов и самодостаточного деплоя (нет внешнего файла → нечему теряться при clone).
// Десятичные (scalingCoefficient, referencePrice) хранятся строками — Prisma
// приводит их к Decimal при записи.

export interface ItemTemplateSeed {
  name: string;
  slotType: string;
  weaponFamily: string | null;
  isTwoHanded: boolean;
  tier: number;
  requiredAttribute: string | null;
  damageDice: string | null;
  bonusCritDice: string | null;
  scalingAttribute: string | null;
  scalingCoefficient: string | null;
  referencePrice: string;
  description: string | null;
}

export const ITEM_TEMPLATES: ItemTemplateSeed[] = [
  {
    name: "Еда Тир 1",
    slotType: "consumable",
    weaponFamily: "food",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "2",
    description: "1 голод",
  },
  {
    name: "Еда Тир 2",
    slotType: "consumable",
    weaponFamily: "food",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "4",
    description: "3 голода",
  },
  {
    name: "Еда Тир 3",
    slotType: "consumable",
    weaponFamily: "food",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "7",
    description: "6 голода",
  },
  {
    name: "Еда Тир 4",
    slotType: "consumable",
    weaponFamily: "food",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "12",
    description: "11 голода",
  },
  {
    name: "Расходники Тир 1",
    slotType: "consumable",
    weaponFamily: "consumable",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "1",
    description: null,
  },
  {
    name: "Расходники Тир 2",
    slotType: "consumable",
    weaponFamily: "consumable",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "3",
    description: null,
  },
  {
    name: "Расходники Тир 3",
    slotType: "consumable",
    weaponFamily: "consumable",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "5",
    description: null,
  },
  {
    name: "Расходники Тир 4",
    slotType: "consumable",
    weaponFamily: "consumable",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "8",
    description: null,
  },
  {
    name: "Одежда Тир 1",
    slotType: "body",
    weaponFamily: "clothing",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "3",
    description: null,
  },
  {
    name: "Одежда Тир 2",
    slotType: "body",
    weaponFamily: "clothing",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "9",
    description: null,
  },
  {
    name: "Одежда Тир 3",
    slotType: "body",
    weaponFamily: "clothing",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "40",
    description: null,
  },
  {
    name: "Одежда Тир 4",
    slotType: "body",
    weaponFamily: "clothing",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "100",
    description: null,
  },
  {
    name: "Инструменты Тир 1",
    slotType: "consumable",
    weaponFamily: "tool",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "2",
    description: null,
  },
  {
    name: "Инструменты Тир 2",
    slotType: "consumable",
    weaponFamily: "tool",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "6",
    description: null,
  },
  {
    name: "Инструменты Тир 3",
    slotType: "consumable",
    weaponFamily: "tool",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "10",
    description: null,
  },
  {
    name: "Инструменты Тир 4",
    slotType: "consumable",
    weaponFamily: "tool",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "19",
    description: null,
  },
  {
    name: "Сила Одноручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "STR_one_hand",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "0.5",
    referencePrice: "10",
    description: "1D6",
  },
  {
    name: "Сила Одноручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "STR_one_hand",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: "2D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "0.5",
    referencePrice: "25",
    description: "2D6",
  },
  {
    name: "Сила Одноручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "STR_one_hand",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: "3D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "0.5",
    referencePrice: "50",
    description: "3D6",
  },
  {
    name: "Сила Одноручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "STR_one_hand",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: "4D8",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "0.5",
    referencePrice: "100",
    description: "4D8",
  },
  {
    name: "Сила Двуручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "STR_two_hand",
    isTwoHanded: true,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "1",
    referencePrice: "17",
    description: "1D6 AOE",
  },
  {
    name: "Сила Двуручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "STR_two_hand",
    isTwoHanded: true,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: "2D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "1",
    referencePrice: "42",
    description: "2D6 AOE",
  },
  {
    name: "Сила Двуручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "STR_two_hand",
    isTwoHanded: true,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: "3D6",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "1",
    referencePrice: "84",
    description: "3D6 AOE",
  },
  {
    name: "Сила Двуручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "STR_two_hand",
    isTwoHanded: true,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: "4D8",
    bonusCritDice: null,
    scalingAttribute: "strength",
    scalingCoefficient: "1",
    referencePrice: "170",
    description: "4D8 AOE",
  },
  {
    name: "Ловкость Одноручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_one_hand",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D4",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "8",
    description: "1D4 + уворот",
  },
  {
    name: "Ловкость Одноручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_one_hand",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D4",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "20",
    description: "2D4 + уворот",
  },
  {
    name: "Ловкость Одноручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_one_hand",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D4",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "40",
    description: "3D4 + уворот",
  },
  {
    name: "Ловкость Одноручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_one_hand",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "80",
    description: "4D6 + 2 уворот",
  },
  {
    name: "Ловкость Двуручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_two_hand",
    isTwoHanded: true,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D4",
    bonusCritDice: "1D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "14",
    description: "1D4 + 1 куб. крита",
  },
  {
    name: "Ловкость Двуручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_two_hand",
    isTwoHanded: true,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D4",
    bonusCritDice: "2D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "35",
    description: "2D4 + 2 куб. крита",
  },
  {
    name: "Ловкость Двуручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_two_hand",
    isTwoHanded: true,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D4",
    bonusCritDice: "3D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "70",
    description: "3D4 + 3 куб. крита",
  },
  {
    name: "Ловкость Двуручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_two_hand",
    isTwoHanded: true,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D6",
    bonusCritDice: "4D6",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "140",
    description: "4D6 + 4 куб. крита",
  },
  {
    name: "Щит Тир 1",
    slotType: "weapon_left",
    weaponFamily: "shield",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "7",
    description: "3 защиты",
  },
  {
    name: "Щит Тир 2",
    slotType: "weapon_left",
    weaponFamily: "shield",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "17",
    description: "6 защиты",
  },
  {
    name: "Щит Тир 3",
    slotType: "weapon_left",
    weaponFamily: "shield",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "34",
    description: "9 защиты",
  },
  {
    name: "Щит Тир 4",
    slotType: "weapon_left",
    weaponFamily: "shield",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "68",
    description: "12 защиты",
  },
  {
    name: "Арбалет Одноручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "13",
    description: "1D6",
  },
  {
    name: "Арбалет Одноручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "33",
    description: "2D6",
  },
  {
    name: "Арбалет Одноручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "66",
    description: "3D6",
  },
  {
    name: "Арбалет Одноручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D8",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "132",
    description: "4D8",
  },
  {
    name: "Арбалет Двуручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: true,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "20",
    description: "1D6 +1D4 to armor",
  },
  {
    name: "Арбалет Двуручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: true,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "50",
    description: "2D6 +2D4 to armor",
  },
  {
    name: "Арбалет Двуручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: true,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D6",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "100",
    description: "3D6 +3D4 to armor",
  },
  {
    name: "Арбалет Двуручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_crossbow",
    isTwoHanded: true,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D8",
    bonusCritDice: null,
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "200",
    description: "4D8 +4D4 to armor",
  },
  {
    name: "Лук Одноручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D4",
    bonusCritDice: "1D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "11",
    description: "1D4 + 1 крит куб",
  },
  {
    name: "Лук Одноручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D4",
    bonusCritDice: "2D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "27",
    description: "2D4 + 2 крит куба",
  },
  {
    name: "Лук Одноручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D4",
    bonusCritDice: "3D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "54",
    description: "3D4 + 3 крит куба",
  },
  {
    name: "Лук Одноручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D6",
    bonusCritDice: "4D6",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.25",
    referencePrice: "180",
    description: "4D6 + 4 крит куба",
  },
  {
    name: "Лук Двуручный Тир 1",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: true,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: "1D4",
    bonusCritDice: "1D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "14",
    description: "1D4 + 1 куб. крита + 1D4 no armor",
  },
  {
    name: "Лук Двуручный Тир 2",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: true,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: "2D4",
    bonusCritDice: "1D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "35",
    description: "2D4 + 1 куб. крита + 1D4 no armor",
  },
  {
    name: "Лук Двуручный Тир 3",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: true,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: "3D4",
    bonusCritDice: "1D4",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "70",
    description: "3D4 + 1 куб. крита + 1D4 no armor",
  },
  {
    name: "Лук Двуручный Тир 4",
    slotType: "weapon_right",
    weaponFamily: "DEX_bow",
    isTwoHanded: true,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: "4D6",
    bonusCritDice: "2D6",
    scalingAttribute: "dexterity",
    scalingCoefficient: "0.5",
    referencePrice: "140",
    description: "4D6 + 2 куб. крита + 1D4 no armor",
  },
  {
    name: "Стрелы Тир 1",
    slotType: "consumable",
    weaponFamily: "ammo",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: "1D4",
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "5",
    description: "1D4",
  },
  {
    name: "Стрелы Тир 2",
    slotType: "consumable",
    weaponFamily: "ammo",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "13",
    description: "1D6",
  },
  {
    name: "Стрелы Тир 3",
    slotType: "consumable",
    weaponFamily: "ammo",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: "1D8",
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "26",
    description: "1D8",
  },
  {
    name: "Стрелы Тир 4",
    slotType: "consumable",
    weaponFamily: "ammo",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: "1D10",
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "52",
    description: "1D10",
  },
  {
    name: "Посох двуруч Тир 1",
    slotType: "weapon_right",
    weaponFamily: "staff",
    isTwoHanded: true,
    tier: 1,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: "intelligence",
    scalingCoefficient: "0.5",
    referencePrice: "20",
    description: "затраты -1",
  },
  {
    name: "Посох двуруч Тир 2",
    slotType: "weapon_right",
    weaponFamily: "staff",
    isTwoHanded: true,
    tier: 2,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: "intelligence",
    scalingCoefficient: "0.5",
    referencePrice: "50",
    description: "затраты -2",
  },
  {
    name: "Посох двуруч Тир 3",
    slotType: "weapon_right",
    weaponFamily: "staff",
    isTwoHanded: true,
    tier: 3,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: "intelligence",
    scalingCoefficient: "0.5",
    referencePrice: "100",
    description: "затраты -3",
  },
  {
    name: "Посох двуруч Тир 4",
    slotType: "weapon_right",
    weaponFamily: "staff",
    isTwoHanded: true,
    tier: 4,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: "intelligence",
    scalingCoefficient: "0.5",
    referencePrice: "200",
    description: "затраты -5",
  },
  {
    name: "Колокольчик одноруч Тир 1",
    slotType: "weapon_right",
    weaponFamily: "bell",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "spirit",
    damageDice: "1D4",
    bonusCritDice: null,
    scalingAttribute: "spirit",
    scalingCoefficient: "0.5",
    referencePrice: "16",
    description: "heal 1D4",
  },
  {
    name: "Колокольчик одноруч Тир 2",
    slotType: "weapon_right",
    weaponFamily: "bell",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "spirit",
    damageDice: "1D6",
    bonusCritDice: null,
    scalingAttribute: "spirit",
    scalingCoefficient: "0.5",
    referencePrice: "32",
    description: "heal 1D6",
  },
  {
    name: "Колокольчик одноруч Тир 3",
    slotType: "weapon_right",
    weaponFamily: "bell",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "spirit",
    damageDice: "1D8",
    bonusCritDice: null,
    scalingAttribute: "spirit",
    scalingCoefficient: "0.5",
    referencePrice: "64",
    description: "heal 1D8",
  },
  {
    name: "Колокольчик одноруч Тир 4",
    slotType: "weapon_right",
    weaponFamily: "bell",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "spirit",
    damageDice: "1D10",
    bonusCritDice: null,
    scalingAttribute: "spirit",
    scalingCoefficient: "0.5",
    referencePrice: "128",
    description: "heal 1D10 + 1 turn duration",
  },
  {
    name: "Мантия Тир 1",
    slotType: "body",
    weaponFamily: "mantle",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "50",
    description: "+10% buble chance",
  },
  {
    name: "Мантия Тир 2",
    slotType: "body",
    weaponFamily: "mantle",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "100",
    description: "+20% buble chance",
  },
  {
    name: "Мантия Тир 3",
    slotType: "body",
    weaponFamily: "mantle",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "200",
    description: "+30% buble chance",
  },
  {
    name: "Мантия Тир 4",
    slotType: "body",
    weaponFamily: "mantle",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "intelligence",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "300",
    description: "+40% buble chance + rerol",
  },
  {
    name: "Ряса Тир 1",
    slotType: "body",
    weaponFamily: "robe",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "spirit",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "40",
    description: "+ 1 turn effect duration",
  },
  {
    name: "Ряса Тир 2",
    slotType: "body",
    weaponFamily: "robe",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "spirit",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "80",
    description: "+ 2 turn effect duration",
  },
  {
    name: "Ряса Тир 3",
    slotType: "body",
    weaponFamily: "robe",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "spirit",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "160",
    description: "+ 3 turn effect duration",
  },
  {
    name: "Ряса Тир 4",
    slotType: "body",
    weaponFamily: "robe",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "spirit",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "220",
    description: "+ 4 turn effect duration",
  },
  {
    name: "Кольцо Тир 1",
    slotType: "ring",
    weaponFamily: "ring",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "16",
    description: "Тир 1 атакующее/лечащее заклинание",
  },
  {
    name: "Кольцо Тир 2",
    slotType: "ring",
    weaponFamily: "ring",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "32",
    description: "Тир 2 атакующее/лечащее заклинание",
  },
  {
    name: "Кольцо Тир 3",
    slotType: "ring",
    weaponFamily: "ring",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "64",
    description: "Тир 3 атакующее/лечащее заклинание",
  },
  {
    name: "Кольцо Тир 4",
    slotType: "ring",
    weaponFamily: "ring",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "128",
    description: "Тир 4 атакующее/лечащее заклинание",
  },
  {
    name: "Ожерелье Тир 1",
    slotType: "amulet",
    weaponFamily: "amulet",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "16",
    description: "Тир 1 баф/дебаф заклинание",
  },
  {
    name: "Ожерелье Тир 2",
    slotType: "amulet",
    weaponFamily: "amulet",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "32",
    description: "Тир 2 баф/дебаф заклинание",
  },
  {
    name: "Ожерелье Тир 3",
    slotType: "amulet",
    weaponFamily: "amulet",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "64",
    description: "Тир 3 баф/дебаф заклинание",
  },
  {
    name: "Ожерелье Тир 4",
    slotType: "amulet",
    weaponFamily: "amulet",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: null,
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "128",
    description: "Тир 4 баф/дебаф заклинание",
  },
  {
    name: "Латы Тир 1",
    slotType: "body",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "20",
    description: "доп хп 6",
  },
  {
    name: "Латы Тир 2",
    slotType: "body",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "50",
    description: "доп хп 12",
  },
  {
    name: "Латы Тир 3",
    slotType: "body",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "70",
    description: "доп хп 18",
  },
  {
    name: "Латы Тир 4",
    slotType: "body",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "100",
    description: "доп хп 24",
  },
  {
    name: "Сапоги (латные) Тир 1",
    slotType: "legs",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "10",
    description: "+1 turn effect resistance",
  },
  {
    name: "Сапоги (латные) Тир 2",
    slotType: "legs",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "30",
    description: "+2 turn effect resistance",
  },
  {
    name: "Сапоги (латные) Тир 3",
    slotType: "legs",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "60",
    description: "+3 turn effect resistance",
  },
  {
    name: "Сапоги (латные) Тир 4",
    slotType: "legs",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "80",
    description: "+4 turn effect resistance",
  },
  {
    name: "Наручи (латные) Тир 1",
    slotType: "vambraces",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "10",
    description: "+1 защиты",
  },
  {
    name: "Наручи (латные) Тир 2",
    slotType: "vambraces",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "30",
    description: "+2 защиты",
  },
  {
    name: "Наручи (латные) Тир 3",
    slotType: "vambraces",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "60",
    description: "+3 защиты",
  },
  {
    name: "Наручи (латные) Тир 4",
    slotType: "vambraces",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "80",
    description: "+4 защиты",
  },
  {
    name: "Шлем Тир 1",
    slotType: "head",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "10",
    description: "-1 крит куб противника",
  },
  {
    name: "Шлем Тир 2",
    slotType: "head",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "30",
    description: "-2 крит куб противника",
  },
  {
    name: "Шлем Тир 3",
    slotType: "head",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "60",
    description: "-3 крит куб противника",
  },
  {
    name: "Шлем Тир 4",
    slotType: "head",
    weaponFamily: "plate",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "strength",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "80",
    description: "-4 крит куб противника",
  },
  {
    name: "Плащи Тир 1",
    slotType: "body",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "10",
    description: "+1 к увороту, доп хп 3",
  },
  {
    name: "Плащи Тир 2",
    slotType: "body",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "30",
    description: "+2 к увороту, доп хп 6",
  },
  {
    name: "Плащи Тир 3",
    slotType: "body",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "60",
    description: "+3 к увороту, доп хп 9",
  },
  {
    name: "Плащи Тир 4",
    slotType: "body",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "90",
    description: "+4 к увороту, доп хп 12",
  },
  {
    name: "Сапоги (кожаные) Тир 1",
    slotType: "legs",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "7",
    description: "доп действие исп. T1 расходник",
  },
  {
    name: "Сапоги (кожаные) Тир 2",
    slotType: "legs",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "20",
    description: "доп действие исп. T2 расходник",
  },
  {
    name: "Сапоги (кожаные) Тир 3",
    slotType: "legs",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "40",
    description: "доп действие исп. T3 расходник",
  },
  {
    name: "Сапоги (кожаные) Тир 4",
    slotType: "legs",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "70",
    description: "доп действие исп. T4 расходник",
  },
  {
    name: "Наручи (кожаные) Тир 1",
    slotType: "vambraces",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "7",
    description: "+1 попадание",
  },
  {
    name: "Наручи (кожаные) Тир 2",
    slotType: "vambraces",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "20",
    description: "+2 попадание",
  },
  {
    name: "Наручи (кожаные) Тир 3",
    slotType: "vambraces",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "40",
    description: "+3 попадание",
  },
  {
    name: "Наручи (кожаные) Тир 4",
    slotType: "vambraces",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "70",
    description: "+4 попадание",
  },
  {
    name: "Капюшон Тир 1",
    slotType: "head",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 1,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "7",
    description: "+1 скрытность",
  },
  {
    name: "Капюшон Тир 2",
    slotType: "head",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 2,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "20",
    description: "+2 скрытность",
  },
  {
    name: "Капюшон Тир 3",
    slotType: "head",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 3,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "40",
    description: "+3 скрытность",
  },
  {
    name: "Капюшон Тир 4",
    slotType: "head",
    weaponFamily: "leather",
    isTwoHanded: false,
    tier: 4,
    requiredAttribute: "dexterity",
    damageDice: null,
    bonusCritDice: null,
    scalingAttribute: null,
    scalingCoefficient: null,
    referencePrice: "70",
    description: "+4 скрытность",
  },
];

/**
 * Идемпотентный сид каталога предметов.
 * Натуральный ключ — `name` ("Категория Тир N"); upsert обновляет существующие.
 * Не каскадит на персонажей: меняются только справочные шаблоны.
 */
export async function seedItemTemplates(prisma: PrismaClient) {
  for (const item of ITEM_TEMPLATES) {
    const data: Prisma.ItemTemplateCreateInput = {
      name: item.name,
      slotType: item.slotType as SlotType,
      weaponFamily: item.weaponFamily,
      isTwoHanded: item.isTwoHanded,
      tier: item.tier,
      requiredAttribute: item.requiredAttribute as StatAttribute | null,
      damageDice: item.damageDice,
      bonusCritDice: item.bonusCritDice,
      scalingAttribute: item.scalingAttribute as StatAttribute | null,
      scalingCoefficient: item.scalingCoefficient,
      referencePrice: item.referencePrice,
      description: item.description,
    };

    await prisma.itemTemplate.upsert({
      where: { name: item.name },
      create: data,
      update: data,
    });
  }

  console.log(`[seed] ItemTemplates: ${ITEM_TEMPLATES.length} upserted`);
}
